import type { Metadata } from "next";
import { Inter, Lexend } from "next/font/google";
import "../styles/globals.scss";

const inter = Inter({ subsets: ["latin"], weight: "400" })

export const metadata: Metadata = {
  title: "Podcastr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <head>

      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}

//37:30