import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Header } from "@/components/Header/header";
import { Player } from "@/components/Player/player";

import "../styles/globals.scss";
import styles from "../styles/app.module.scss";

const inter = Inter({ subsets: ["latin"], weight: "400" })

export const metadata: Metadata = {
  title: "Podcastr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className={inter.className}>
        <div className={styles.wrapper}>
          <main>
            <Header />
            {children}
          </main>
          <Player />
        </div>
      </body>
    </html>
  );
}